### ISSUE TITLE
Eksik kalan kısımlar için çeviri önerisi

### ISSUE THREAD

**Issue by oguzcankoseoglu** [dnomak/dnomak.com#1]
https://github.com/dnomak/dnomak.com/blob/nuxt/locales/en.json

line02: My name is Doğukan Güven Nomak. I work as a Frontend Developer in Istanbul.
line03: We are producing videos together with Developers and Designers on YouTube for increasing our motivation and love for this job.
desc: SVG Turkey Map contains apart İstanbul Asia and Europe, Cyprus. Also Responsive :)

**Comment by dnomak** [comment]
süpersin ya gerçekten çok teşekkür ederim :) şunun içinde yardımcı olabilir misin :)

"Tüm sohbetleri Yavuz Kömeçoğlu tarafından hazırlanan Humans Chatbot'u kullanarak görüntüleyin."
