### ISSUE TITLE
Scrool Bar Tasarımlarının Değişmesi.

### ISSUE THREAD

**Issue by ukeskin** [dnomak/dnomak.com#12]
**Scrool barın güzel durmadığını düşündüm ve scrool bar tasarladım.**
https://codepen.io/ukeskin/pen/vZdbem

**Comment by ukeskin** [comment]
Abi direk kodun içine koyamadım biraz acemiyim de kusura bakma -_-

**Comment by abdullah** [comment]
Native scroll ile oynamak kullanıcı deneyimi açısından kötü olabilir.

@ukeskin https://opensource.guide/how-to-contribute/ buraya bakabilirsin.

**Comment by dnomak** [comment]
@ukeskin scroll konusunda bende aynı fikirdeyim. @abdullah'ın attığı link oldukça faydalı. ek olarak @fatihacet'in hazırladığı şu videoyu izle mutlaka :) https://youtu.be/OAvYk9-i1y0 bu projenin genel amaçlarından birisi de bu aslında ufakta olsa yavaş yavaş projeye bir kısımdan sizin gibi arkadaşlarıda dahil olmasını sağlamak. aklına takılan kısımlar olursa yaz tekrar :)

**Comment by dnomak** [comment]
@ukeskin ek olarak şu videoyu da izle mutlaka https://youtu.be/H8BW0g9UI_M

**Comment by traderxc** [comment]
Sen buna tasarladım demişsin ama bu hazır zaten :D https://codepen.io/abhishekp1996/pen/JXYBmp

**Comment by dnomak** [comment]
@ukeskin bir şeyler yapmak için çaba gösteriyoruz uğraşıyoruz heves kırıcı yorum geldimi vallahi çok üzülüyorum o yüzden traderxc'in yorumunu kaldırdım mail'de geldiyse görmezden gel umursama rica ediyorum.

**Comment by ukeskin** [comment]
Yok zaten umursamadım sonuçta adam codepen insan kullansın referans alsin diye koymuş.
