### ISSUE TITLE
Video dakikasına göre sorunun aktif olması

### ISSUE THREAD

**Issue by falconsw** [dnomak/dnomak.com#15]
öncelikle tebrik ederim kardeşim mükemmel bir proje.
benim küçük bir önerim var. video akarken sağdaki başlıklarıda işaretleyebiliyor olması. bu mümkün olursa mükemmel olur bence. nacizane fikrim

**Comment by dnomak** [comment]
güzel yorumların için çok teşekkür ederim :) bahsettiğin özellik müthiş olur gerçekten youtube api kısmında 1 yıldır düzeltilmeyen buglardan kaynaklı sıkıntılar oluyor ama uğraşalım üstüne.

**Comment by dnomak** [comment]
@falconsw özellik yayına alındı ama video hızlandırılmış şekilde izlendiğinde player zamanıyla soru zamanı eşitlenmeden geçebiliyor bu kısma daha sonra tekrar bakacağım ama şuan gayet güzel oldu teşekkür ederim :) 

https://github.com/dnomak/dnomak.com/commit/015934aeb81f7619379e9f5294a44c1d25a5e561

**Comment by falconsw** [comment]
harikasın. eline sağlık.
