### ISSUE TITLE
Humans divinde iki scroll barın bulunması

### ISSUE THREAD

**Issue by tgrlgnc** [dnomak/dnomak.com#2]
chrome;
![scroll-bar](https://user-images.githubusercontent.com/8015587/29789570-1b9f45b4-8c3f-11e7-84f3-a0f5168edff6.png)
firefox;
![scroll2](https://user-images.githubusercontent.com/8015587/29789662-7494bde8-8c3f-11e7-8b70-687a791611d5.png)

Çözüm;
En dıştaki scroll barı kaldırmak için;
components/SidebarHumans.vue dosyası 6. satırın
`    .xl-ba-white.xl-fs14.xl-lh20.xl-br8.xl-bo-gray-200.xl-bw2.xl-os
`
sonundaki .xl-os classının çıkarılması
`    .xl-ba-white.xl-fs14.xl-lh20.xl-br8.xl-bo-gray-200.xl-bw2
`

components/SidebarHumans.vue dosyası 58. satırdaki .humans classına aşağıdaki özelliğin eklenmesi;
eski;
` .humans {
    max-height: 284px;
    overflow: scroll;
  }`
eklendikten sonraki hali;
` .humans {
    max-height: 284px;
    overflow: scroll;
    overflow-x: hidden;
  }`

Düzeltilmiş hali;
chrome;
![scroll-end](https://user-images.githubusercontent.com/8015587/29789712-a82e7446-8c3f-11e7-9588-0ad545c8826d.png)
firefox;
![firefox-last](https://user-images.githubusercontent.com/8015587/29790313-112f0c56-8c42-11e7-9aa1-256b15795ea5.png)

**Comment by dnomak** [comment]
teşekkür ederim.

**Comment by dnomak** [comment]
bu durum düzeltildi.
