### ISSUE TITLE
Arama işlevi

### ISSUE THREAD

**Issue by VictorTomaili** [dnomak/dnomak.com#2]
Sayfanın en üstünde full-width olarak bir arama alanı bulunması, içeriğe ulaşmak konusunda kolaylık sağlayacağını düşünüyorum. Önerilerim şöyle;

- Full-width arama alanı
- İçeriğe ait #tag kullanarak (teknoloji, ilgi alanları, çalışılan şirket ve projeler) arama yapacak kişiye kolaylık sağlanabilir. Popüler tag listesi arama çubuğunun altında listelenebilir. 
- Videoların içeriği tamamen metin hale getirilirse arama yapılırken sonuçlara ulaşmak kolay olacaktır.

**Comment by dnomak** [comment]
@VictorTomaili https://github.com/dnomak/dnomak.com/pull/14 şu şekilde bir ekleme yaptı buna ek düzenlemeler yapıp bu işi kapatacağım.

**Comment by dnomak** [comment]
https://github.com/dnomak/dnomak.com/pull/16
