### ISSUE TITLE
Hero sıralaması

### ISSUE THREAD

**Issue by dnomak** [dnomak/dnomak.com#4]
http://dnomak.com/heroes sayfasındaki hero'ların sıralamaları son yayınlanan videoya göre yapılmalıdır.

**Comment by abdullah** [comment]
```
{
    allTags {
    name
    heroes(orderBy: id_DESC) {
      name
      title
      username
    }
  }
}
```

Bu sorgu yeterli mi? 

Video tarihleri ile alakalı bir şey bulamadım var ise ya da sorgunun nasıl olması gerektiğini paylaşırsan daha kolay olur katkıda bulunmak isteyenler için. 👍

**Comment by dnomak** [comment]
çok mantıklı `orderBy: createdAt_DESC`kullansak daha iyi sanırım videoların yayınlanma tarihini tutmuyorum ama yaratma tarihi doğru sıralamada.

**Comment by dnomak** [comment]
desteğin için teşekkür ederim @abdullah değişikliği yapıp işi kapattım.
